// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2evfRxX1-WKBIH-8WZeUyZ2H4knjvMDE',
    appId: '1:961039999550:web:8695a7d155e9c5bdd8e76f',
    messagingSenderId: '961039999550',
    projectId: 'docdoc-app-b6a80',
    authDomain: 'docdoc-app-b6a80.firebaseapp.com',
    storageBucket: 'docdoc-app-b6a80.firebasestorage.app',
    measurementId: 'G-8Z56KJP92V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiowAORv939wSh2Zl1FZdiIdIIha5xDfM',
    appId: '1:961039999550:android:d2ff273c886f0f85d8e76f',
    messagingSenderId: '961039999550',
    projectId: 'docdoc-app-b6a80',
    storageBucket: 'docdoc-app-b6a80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCGCmV2084pwp6V1bnJdTgcsP7wu206H0',
    appId: '1:961039999550:ios:2001e2bc4601ceccd8e76f',
    messagingSenderId: '961039999550',
    projectId: 'docdoc-app-b6a80',
    storageBucket: 'docdoc-app-b6a80.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdvancedCourseOmarAhmed',
  );

}