# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lanes for firebase distribution app"
  lane :distribute do
    sh "flutter clean"
    sh "flutter build apk --no-tree-shake-icons --flavor production -t lib/main_production.dart"
    firebase_app_distribution(
      app: "1:961039999550:android:d2ff273c886f0f85d8e76f",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "m.elsherbeny100100@gmail.com",
      release_notes: "First Fastlane Distribution",
    )
  end
end
